#!/bin/sh
set -x
set -e

arch="`dpkg --print-architecture`"
case "$arch" in
  i386)
    host=i686-w64-mingw32
    ;;
  amd64)
    host=x86_64-w64-mingw32
    ;;
  *)
    echo >&2 "Unexpected architecture $ARCHITECTURE."
    exit 1
    ;;
esac

rm -rf UPSTREAM RESULT
for lib in zlib openssl libevent; do
  tb="ARCHITECTURE=$arch,SUITE=$SUITE"/RESULT.$lib.tar.gz
  if ! [ -e "$tb" ]; then
    echo >&2 "Did not find $tb."
    exit 1
  fi
  tar xavf "$tb" --transform 's#^RESULT/#UPSTREAM/#'
  rm "$tb"
done

BASE="`pwd`"
(cd tor
  ./autogen.sh

  echo "=== [build] running configure ==="
  ./configure \
    --disable-silent-rules \
    --disable-asciidoc \
    --host="$host" \
    --with-libevent-dir="$BASE/UPSTREAM" \
    --with-openssl-dir="$BASE/UPSTREAM" \
    --with-zlib-dir="$BASE/UPSTREAM" \
    --prefix=/ \
    --enable-gcc-warnings \
    && rc=0 || rc=$?
  if [ "$rc" != 0 ]; then
    echo "=== [build] FAILED: configure ==="
    echo >&2 "============================="
    echo >&2 "Configure failed.  Trying to cat config.log."
    echo >&2 "============================="
    cat config.log || true
    exit $rc
  fi

  echo "=== [build] running make ==="
  make -k install DESTDIR="$BASE/RESULT" && rc=0 || rc=$?
  if [ "$rc" != 0 ]; then
    echo >&2 "============================="
    echo >&2 "make -k failed.  Re-running without -k to maybe see the error near the end of the build-log."
    echo >&2 "============================="
    make install DESTDIR="$BASE/RESULT" || true
    echo "=== [build] FAILED: make ==="
    exit $rc
  fi

  cp src/test/test.exe "$BASE/RESULT/bin/"
  cp src/test/test-process.exe "$BASE/RESULT/bin/"
)

cp -v UPSTREAM/bin/*dll RESULT/bin
install -v -m 755 /usr/lib/gcc/$host/*-win32/libssp-0.dll RESULT/bin/
if [ "$arch" = i386 ]; then
  install -v -m 755 /usr/lib/gcc/$host/*-win32/libgcc_s_sjlj-1.dll RESULT/bin/
fi

tar czf RESULT.tor.tar.gz RESULT
