#!/bin/bash

set -e
set -x
set -u

cleanup() {
    if [ -n "$base" ]; then
        cd "$base" && rm -rf website
    fi
}

base="$(pwd)"
repo="$(basename $base)"

echo "Building $repo"

trap 'cleanup' EXIT
rm -rf RESULT

gitrev="$(cd website && git rev-parse HEAD)"

case "$repo" in
  lektor-website-support-translation-any|lektor-website-tor-browser-manual-translation-any|lektor-website-tpo-translation-any|lektor-website-support-translation|lektor-website-tor-browser-manual-translation)
    translationgit="$base/translation"
    translationrev="$(cd translation && git rev-parse HEAD)"

    echo "Syncing translation with rev $translationrev"

    (
    cd translation && cp -v *.po "$base/website/i18n/"
    )
    ;;
esac

echo "Building branch $GIT_BRANCH with rev $gitrev"

(
cd website
LC_ALL=C.UTF-8 lektor plugin reinstall
echo "Building lektor a few times to make sure translation files are generated"
for i in {1..4}
do
   LC_ALL=C.UTF-8 lektor build -O public
done
)

mv website/public output
mkdir -p output/project/trace
( date -u
  echo "Built on `hostname`."
  echo "Based on $gitrev."
) > output/project/trace/jenkins.torproject.org

if [ -n "${GIT_BRANCH:-}" ]; then
  echo "${GIT_BRANCH#origin/}" > output/project/trace/branch
fi

mkdir RESULT
tar -caf RESULT/output.tar.gz output
