#!/bin/bash

set -e
set -x
set -u

cleanup() {
    if [ -n "$base" ]; then
        cd "$base" && rm -rf website
    fi
}
base="$(pwd)"

trap 'cleanup' EXIT
rm -rf RESULT

gitrev=$(cd website && git rev-parse HEAD)
echo "Building $GIT_BRANCH with rev $gitrev"

(
cd website
LC_ALL=C.UTF-8 lektor plugin reinstall
LC_ALL=C.UTF-8 lektor build -O public
)

mv website/public output
mkdir -p output/project/trace
( date -u
  echo "Built on `hostname`."
  echo "Based on $gitrev."
) > output/project/trace/jenkins.torproject.org

if [ -n "${GIT_BRANCH:-}" ]; then
  echo "${GIT_BRANCH#origin/}" > output/project/trace/branch
fi

mkdir RESULT
tar -caf RESULT/output.tar.gz output
